let fieldsAndPaths = {
    title: ["h1"],
    images: [".classifiedDetailMainPhoto img", "imgs2b64($, img => img.dataset.src || img.src)", "array"],
    breadcrumb: [".search-result-bc .bc-item", "elsToText($, ' > ')"],
    price: ".classified-price-wrapper",
    location: ".classifiedInfo h2",
    coords: ["#gmap", "[$0.dataset.lat, $0.dataset.lon]", "array"],
    listingId: ["text=İlan No", "$0.nextElementSibling"],
    listingDate: ["text=İlan Tarihi", "$0.nextElementSibling"],
    brand: ["text=Marka", "$2.nextElementSibling"],
    series: ["text=Seri", "$0.nextElementSibling"],
    model: ["text=Model", "$0.nextElementSibling"],
    year: ["text=Yıl", "$0.nextElementSibling"],
    fuelType: ["text=Yakıt Tipi", "$0.nextElementSibling"],
    transmission: ["text=Vites", "$0.nextElementSibling"],
    state: ["text=Araç Durumu", "$1.nextElementSibling"],
    mileage: ["text=KM", "$0.nextElementSibling"],
    bodyType: ["text=Kasa Tipi", "$0.nextElementSibling"],
    enginePower: ["text=Motor Gücü", "$0.nextElementSibling"],
    engineVolume: ["text=Motor Hacmi", "$0.nextElementSibling"],
    Çekiş: ["text=Çekiş", "$0.nextElementSibling"],
    color: ["text=Renk", "$0.nextElementSibling"],
    warranty: ["text=Garanti", "$0.nextElementSibling"],
    heavilyDamaged: ["text=Ağır Hasar Kayıtlı", "$0.nextElementSibling"],
    licencePlate: ["text=Plaka / Uyruk", "$0.nextElementSibling"],
    lister: ["text=Kimden", "$0.nextElementSibling"],
    trade: ["text=Takas", "$0.nextElementSibling"],
    storeLogo: [".user-info-store-logo img", "img2b64($0)"],
    storeName: [".user-info-store-name a"],
    storeLink: [".user-info-store-name a", "$0.href"],
    storeAgentName: [".user-info-agent h3"],
    storeAgentMobilePhone: [".user-info-phones", "text=Cep", "$0.nextElementSibling"],
    username: [".username-info-area span", `getComputedStyle($0, "::before").content`],
    userRegistrationDate: ".userRegistrationDate span",
    userMobilePhone: [".pretty-phone-part span", `$0.dataset.content`],
    description: "#classified-detail .uiBoxContainer",
    parts: {
        frontBumper: getCarPartStatus.bind(null, ["Ön Tampon"]),
        frontHood: getCarPartStatus.bind(null, ["Motor Kaputu"]),
        roof: getCarPartStatus.bind(null, ["Tavan"]),
        rearHood: getCarPartStatus.bind(null, ["Bagaj Kapağı"]),
        rearBumper: getCarPartStatus.bind(null, ["Arka Tampon"]),
        
        frontLeftFender: getCarPartStatus.bind(null, ["Sol Ön Çamurluk"]),
        frontLeftDoor: getCarPartStatus.bind(null, ["Sol Ön Kapı"]),
        rearLeftDoor: getCarPartStatus.bind(null, ["Sol Arka Kapı"]),
        rearLeftFender: getCarPartStatus.bind(null, ["Sol Arka Çamurluk"]),
        
        frontRightFender: getCarPartStatus.bind(null, ["Sağ Ön Çamurluk"]),
        frontRightDoor: getCarPartStatus.bind(null, ["Sağ Ön Kapı"]),
        rearRightDoor: getCarPartStatus.bind(null, ["Sağ Arka Kapı"]),
        rearRightFender: getCarPartStatus.bind(null, ["Sağ Arka Çamurluk"]),
    },
    feats: {
        security: {
            abs: ["#classifiedProperties", "text=ABS", "$0.classList.contains('selected')"],
            aeb: ["#classifiedProperties", "text=AEB", "$0.classList.contains('selected')"],
            bas: ["#classifiedProperties", "text=BAS", "$0.classList.contains('selected')"],
            childLock: ["#classifiedProperties", "text=Çocuk Kilidi", "$0.classList.contains('selected')"],
            distronic: ["#classifiedProperties", "text=Distronic", "$0.classList.contains('selected')"],
            esp_vsa: ["#classifiedProperties", "text=ESP / VSA", "$0.classList.contains('selected')"],
            nightVision: ["#classifiedProperties", "text=Gece Görüş Sistemi", "$0.classList.contains('selected')"],
            driverAirbag: ["#classifiedProperties", "text=Hava Yastığı (Sürücü)", "$0.classList.contains('selected')"],
            passengerAirbag: [
                "#classifiedProperties",
                "text=Hava Yastığı (Yolcu)",
                "$0.classList.contains('selected')",
            ],
            immobilizer: ["#classifiedProperties", "text=Immobilizer", "$0.classList.contains('selected')"],
            isofix: ["#classifiedProperties", "text=Isofix", "$0.classList.contains('selected')"],
            blindSpotWarning: [
                "#classifiedProperties",
                "text=Kör Nokta Uyarı Sistemi",
                "$0.classList.contains('selected')",
            ],
            centralLock: ["#classifiedProperties", "text=Merkezi Kilit", "$0.classList.contains('selected')"],
            laneKeepingAssist: [
                "#classifiedProperties",
                "text=Şerit Takip Sistemi",
                "$0.classList.contains('selected')",
            ],
            hillStartAssist: [
                "#classifiedProperties",
                "text=Yokuş Kalkış Desteği",
                "$0.classList.contains('selected')",
            ],
            fatigueDetection: [
                "#classifiedProperties",
                "text=Yorgunluk Tespit Sistemi",
                "$0.classList.contains('selected')",
            ],
            armoredVehicle: ["#classifiedProperties", "text=Zırhlı Araç", "$0.classList.contains('selected')"],
        },
        interior: {
            acc: ["#classifiedProperties", "text=Adaptive Cruise Control", "$0.classList.contains('selected')"],
            keylessEntryAndStart: [
                "#classifiedProperties",
                "text=Anahtarsız Giriş ve Çalıştırma",
                "$0.classList.contains('selected')",
            ],
            leatherSeats: ["#classifiedProperties", "text=Deri Koltuk", "$0.classList.contains('selected')"],
            electricWindows: ["#classifiedProperties", "text=Elektrikli Camlar", "$0.classList.contains('selected')"],
            functionalSteering: [
                "#classifiedProperties",
                "text=Fonksiyonel Direksiyon",
                "$0.classList.contains('selected')",
            ],
            rearViewCamera: ["#classifiedProperties", "text=Geri Görüş Kamerası", "$0.classList.contains('selected')"],
            headUpDisplay: ["#classifiedProperties", "text=Head-up Display", "$0.classList.contains('selected')"],
            cruiseControl: ["#classifiedProperties", "text=Hız Sabitleme Sistemi", "$0.classList.contains('selected')"],
            hydraulicSteering: [
                "#classifiedProperties",
                "text=Hidrolik Direksiyon",
                "$0.classList.contains('selected')",
            ],
            heatedSteeringWheel: [
                "#classifiedProperties",
                "text=Isıtmalı Direksiyon",
                "$0.classList.contains('selected')",
            ],
            climateControl: ["#classifiedProperties", "text=Klima", "$0.classList.contains('selected')"],
            electricSeats: [
                "#classifiedProperties",
                "text=Koltuklar (Elektrikli)",
                "$0.classList.contains('selected')",
            ],
            memorySeats: ["#classifiedProperties", "text=Koltuklar (Hafızalı)", "$0.classList.contains('selected')"],
            heatedSeats: ["#classifiedProperties", "text=Koltuklar (Isıtmalı)", "$0.classList.contains('selected')"],
            cooledSeats: ["#classifiedProperties", "text=Koltuklar (Soğutmalı)", "$0.classList.contains('selected')"],
            fabricSeats: ["#classifiedProperties", "text=Kumaş Koltuk", "$0.classList.contains('selected')"],
            autoDimmingRearviewMirror: [
                "#classifiedProperties",
                "text=Otm.Kararan Dikiz Aynası",
                "$0.classList.contains('selected')",
            ],
            frontViewCamera: ["#classifiedProperties", "text=Ön Görüş Kamerası", "$0.classList.contains('selected')"],
            frontSeatArmrest: [
                "#classifiedProperties",
                "text=Ön Koltuk Kol Dayaması",
                "$0.classList.contains('selected')",
            ],
            cooledGloveBox: ["#classifiedProperties", "text=Soğutmalı Torpido", "$0.classList.contains('selected')"],
            startStop: ["#classifiedProperties", "text=Start / Stop", "$0.classList.contains('selected')"],
            thirdRowSeats: ["#classifiedProperties", "text=Üçüncü Sıra Koltuklar", "$0.classList.contains('selected')"],
            tripComputer: ["#classifiedProperties", "text=Yol Bilgisayarı", "$0.classList.contains('selected')"],
        },
        exterior: {
            footActivatedTrunk: [
                "#classifiedProperties",
                "text=Ayakla Açılan Bagaj Kapağı",
                "$0.classList.contains('selected')",
            ],
            hardtop: ["#classifiedProperties", "text=Hardtop", "$0.classList.contains('selected')"],
            adaptiveHeadlights: ["#classifiedProperties", "text=Far (Adaptif)", "$0.classList.contains('selected')"],
            electricMirrors: [
                "#classifiedProperties",
                "text=Aynalar (Elektrikli)",
                "$0.classList.contains('selected')",
            ],
            heatedMirrors: ["#classifiedProperties", "text=Aynalar (Isıtmalı)", "$0.classList.contains('selected')"],
            memoryMirrors: ["#classifiedProperties", "text=Aynalar (Hafızalı)", "$0.classList.contains('selected')"],
            rearParkingSensors: [
                "#classifiedProperties",
                "text=Park Sensörü (Arka)",
                "$0.classList.contains('selected')",
            ],
            frontParkingSensors: [
                "#classifiedProperties",
                "text=Park Sensörü (Ön)",
                "$0.classList.contains('selected')",
            ],
            parkAssist: ["#classifiedProperties", "text=Park Asistanı", "$0.classList.contains('selected')"],
            sunroof: ["#classifiedProperties", "text=Sunroof", "$0.classList.contains('selected')"],
            smartTrunk: ["#classifiedProperties", "text=Akıllı Bagaj Kapağı", "$0.classList.contains('selected')"],
            panoramicSunroof: [
                "#classifiedProperties",
                "text=Panoramik Cam Tavan",
                "$0.classList.contains('selected')",
            ],
            towHook: ["#classifiedProperties", "text=Römork Çeki Demiri", "$0.classList.contains('selected')"],
        },
        multimedia: {
            androidAuto: ["#classifiedProperties", "text=Android Auto", "$0.classList.contains('selected')"],
            appleCarPlay: ["#classifiedProperties", "text=Apple CarPlay", "$0.classList.contains('selected')"],
            bluetooth: ["#classifiedProperties", "text=Bluetooth", "$0.classList.contains('selected')"],
            usbAux: ["#classifiedProperties", "text=USB / AUX", "$0.classList.contains('selected')"],
        },
    },
    modelName: [".tech-main-title span"],
    specs: {
        general: {
            modelYear: ["text=Model Üretim Yılı (İlk / Son)", "$0.nextElementSibling"],
            segment: ["text=Segmenti", "$0.nextElementSibling"],
            bodyType: ["text=Kasa Tipi / Kapı Sayısı", "$0.nextElementSibling"],
            engineType: ["text=Motor Tipi", "$0.nextElementSibling"],
            fuelConsumption: ["text=Yakıt Tüketimi (Şehir içi / Şehir dışı)", "$0.nextElementSibling"],
            enginePower: ["text=Motor Gücü", "$0.nextElementSibling"],
            transmission: ["text=Şanzıman / Çekiş", "$0.nextElementSibling"],
            acceleration: ["text=Hızlanma 0-100 km/saat", "$0.nextElementSibling"],
            topSpeed: ["text=Azami Sürat", "$0.nextElementSibling"],
            annualTax: ["text=/Toplam yıllık MTV \\(\\d+ model ve \\d+ cc\\)/", "$0.nextElementSibling"],
        },
        engine: {
            engineType: ["text=Motor Tipi", "$0.nextElementSibling"],
            engineCapacity: ["text=Motor Hacmi", "$0.nextElementSibling"],
            maxPower: ["text=Maksimum Güç", "$0.nextElementSibling"],
            maxTorque: ["text=Maksimum Tork", "$0.nextElementSibling"],
            acceleration: ["text=Hızlanma 0-100 km/saat", "$0.nextElementSibling"],
            topSpeed: ["text=Azami Sürat", "$0.nextElementSibling"],
        },
        fuelConsumption: {
            fuelType: ["text=Yakıt Tipi", "$0.nextElementSibling"],
            cityConsumption: ["text=Şehir içi (100 km'de)", "$0.nextElementSibling"],
            highwayConsumption: ["text=Şehir dışı (100 km'de)", "$0.nextElementSibling"],
            averageConsumption: ["text=Ortalama (100 km'de)", "$0.nextElementSibling"],
            fuelTankCapacity: ["text=Yakıt Depo Hacmi", "$0.nextElementSibling"],
        },
        dimensions: {
            seatingCapacity: ["text=Koltuk Sayısı", "$0.nextElementSibling"],
            length: ["text=Uzunluk", "$0.nextElementSibling"],
            width: ["text=Genişlik", "$0.nextElementSibling"],
            height: ["text=Yükseklik", "$0.nextElementSibling"],
            curbWeight: ["text=Net Ağırlık", "$0.nextElementSibling"],
            trunkCapacity: ["text=Bagaj Kapasitesi", "$0.nextElementSibling"],
            tireDimensions: ["text=Lastik Ölçüleri", "$0.nextElementSibling"],
        },
        equipments: {
            security: {
                abs: [".equipments", "text=ABS", "$0.nextElementSibling", "$0.classList.contains('checkmark')"],
                "Çarpışma Uyarı Sistemi - Sürücü Izleme": [
                    ".equipments",
                    "text=Çarpışma Uyarı Sistemi - Sürücü Izleme",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Çoklu Çarpışma Frenlemesi": [
                    ".equipments",
                    "text=Çoklu Çarpışma Frenlemesi",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Devrilme Kontrol Sistemi (ESC)": [
                    ".equipments",
                    "text=Devrilme Kontrol Sistemi (ESC)",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                EBD: [".equipments", "text=EBD", "$0.nextElementSibling", "$0.classList.contains('checkmark')"],
                "ESP (Denge Kontrolü)": [
                    ".equipments",
                    "text=ESP (Denge Kontrolü)",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Fren Yardım Sistemi (Brake Assist System)": [
                    ".equipments",
                    "text=Fren Yardım Sistemi (Brake Assist System)",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Geri Görüş Aynası - Otomatik Kararan": [
                    ".equipments",
                    "text=Geri Görüş Aynası - Otomatik Kararan",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                Isofix: [".equipments", "text=Isofix", "$0.nextElementSibling", "$0.classList.contains('checkmark')"],
                "Lastik Basınç Kontrolü": [
                    ".equipments",
                    "text=Lastik Basınç Kontrolü",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Merkezi Kilit": [
                    ".equipments",
                    "text=Merkezi Kilit",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Otomatik Dörtlü Flaşör": [
                    ".equipments",
                    "text=Otomatik Dörtlü Flaşör",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Sürücü Hava Yastığı": [
                    ".equipments",
                    "text=Sürücü Hava Yastığı",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Yokuşta Kalkış Desteği": [
                    ".equipments",
                    "text=Yokuşta Kalkış Desteği",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Yolcu Hava Yastığı": [
                    ".equipments",
                    "text=Yolcu Hava Yastığı",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
            },
            interior: {
                Klima: [".equipments", "text=Klima", "$0.nextElementSibling", "$0.classList.contains('checkmark')"],
                "Ön Koltuk Kol Dayaması": [
                    ".equipments",
                    "text=Ön Koltuk Kol Dayaması",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Start/Stop": [
                    ".equipments",
                    "text=Start/Stop",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
            },
            exterior: {
                "Arka Cam - Isıtmalı Arka Cam": [
                    ".equipments",
                    "text=Arka Cam - Isıtmalı Arka Cam",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Cam Tavan": [
                    ".equipments",
                    "text=Cam Tavan",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Park Yardım Sistemi": [
                    ".equipments",
                    "text=Park Yardım Sistemi",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Yan Aynalar - Isıtmalı": [
                    ".equipments",
                    "text=Yan Aynalar - Isıtmalı",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Yan Aynalar - Otomatik Kararan": [
                    ".equipments",
                    "text=Yan Aynalar - Otomatik Kararan",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
            },
            comfort: {
                "Elektrikli Bagaj Kapama": [
                    ".equipments",
                    "text=Elektrikli Bagaj Kapama",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Elektrikli Camlar": [
                    ".equipments",
                    "text=Elektrikli Camlar",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Elektrikli Katlanabilen Aynalar": [
                    ".equipments",
                    "text=Elektrikli Katlanabilen Aynalar",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Gündüz Yanan Farlar": [
                    ".equipments",
                    "text=Gündüz Yanan Farlar",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Hız Sabitleme Sistemi": [
                    ".equipments",
                    "text=Hız Sabitleme Sistemi",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Ön Far Ayarlama - Sürüşe Duyarlı Farlar": [
                    ".equipments",
                    "text=Ön Far Ayarlama - Sürüşe Duyarlı Farlar",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Smart Card / Smart Key": [
                    ".equipments",
                    "text=Smart Card / Smart Key",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
                "Trafik Bilgi Sistemi": [
                    ".equipments",
                    "text=Trafik Bilgi Sistemi",
                    "$0.nextElementSibling",
                    "$0.classList.contains('checkmark')",
                ],
            },
        },
    },
};